#!/command/with-contenv bash

# 检查config配置文件，并创建
if [ ! -e "/config/qBittorrent/config/qBittorrent.conf" ] ;  then 
    mkdir -p /config/qBittorrent/config/
    cp /usr/local/qbittorrent/defaults/qBittorrent.conf /config/qBittorrent/config/qBittorrent.conf
    python /etc/s6-overlay/scripts/generate-passwd /config/qBittorrent/config/qBittorrent.conf
fi

# 检查Search文件，并创建.
if [ ! -d "/config/qBittorrent/data/nova3/engines" ] ;  then 
    mkdir -p /config/qBittorrent/data/nova3/engines
fi
cp -ru /usr/local/qbittorrent/defaults/Search/*  /config/qBittorrent/data/nova3/engines

# permissions
allow_download_dir=$(/command/s6-setuidgid abc sh -c 'test -w /downloads;echo $?')
allow_config_dir=$(/command/s6-setuidgid abc sh -c 'test -w /config;echo $?')

perms=($allow_config_dir $allow_download_dir)
messages=(
    "Permssion of configuration directory is set properly."
    "Permssion of download directory is set properly."
)
errors=(
    "Permssion of configuration directory is not set properly, try to set now..."
    "Permssion of download directory is not set properly, try to set now..."
)
dirs=(
    /config
    /downloads
)

for i in $(seq 0 1 1)
do
    if [ "${perms[$i]}" -eq "0" ];then
        echo "${messages[$i]}"
    else
        echo "${errors[$i]}"
        chown -R abc:abc ${dirs[$i]}
    fi
done
