name: Manual Upload files to release

on:
  workflow_dispatch:

jobs:
  buildx:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # 获得仓库中的ReleaseTag
      - name: Set Version
        id: set-version
        run: |
          echo "::set-output name=version::$(cat ReleaseTag | head -n1)"
          echo "ReleaseTag=$(cat ReleaseTag | head -n1)"

      - name: Dowload files
        run: |
          mkdir ./qbittorrent
          cd ./qbittorrent
          wget -q https://github.com/c0re100/qBittorrent-Enhanced-Edition/releases/download/release-${{ steps.set-version.outputs.version }}/qbittorrent-nox_x86_64-linux-musl_static.zip
          wget -q https://github.com/c0re100/qBittorrent-Enhanced-Edition/releases/download/release-${{ steps.set-version.outputs.version }}/qbittorrent-nox_arm-linux-musleabi_static.zip
          wget -q https://github.com/c0re100/qBittorrent-Enhanced-Edition/releases/download/release-${{ steps.set-version.outputs.version }}/qbittorrent-nox_aarch64-linux-musl_static.zip

      - name: Upload files to release
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          name: qBittorrent Enhanced Edition v${{ steps.set-version.outputs.version }}
          tag_name: ${{ steps.set-version.outputs.version }}
          # body_path: Changelog
          files: |
            ./qbittorrent/*.zip
