#!/usr/bin/with-contenv bash

# 检查config配置文件，并创建
if [ ! -e "/config/qBittorrent/config/qBittorrent.conf" ]; then
    mkdir -p /config/qBittorrent/config/
    cp /usr/local/qbittorrent/defaults/qBittorrent.conf /config/qBittorrent/config/qBittorrent.conf
fi

# 检查Search文件，并创建.
if [ ! -d "/config/qBittorrent/data/nova3/engines" ]; then
    mkdir -p /config/qBittorrent/data/nova3/engines
fi
cp -ru /usr/local/qbittorrent/defaults/Search/* /config/qBittorrent/data/nova3/engines

# permissions
chown -R abc:abc /config

# 判断是否需要开启对 /downloads 文件夹进行权限修复操作
if [ "$ENABLE_DOWNLOADS_PERM_FIX" = "true" ]; then
    # 修改权限
    chown -R abc:abc /downloads
fi
